[package]
name = "docmeta"
version = "0.3.2"
authors = ["Even Solberg"]
edition = "2021"
include = ["src/main.rs", "README.md"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.18", features = ["cargo", "color"] }
env_logger = "0.11.1"
epub = "2.1.1"
log = "0.4.16"
mobi = "0.8.0"
pdf = "0.7.2"

[dev-dependencies]
assay = "0.1.1"

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
panic = 'abort'
